name: news-tools

services:
  bot:
    build: 
      context: ./news-tools-core
      args:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - .env
    ports:
      - "${API_PORT}:8080"
    volumes:
      - bot-alembic:/lib/news-alembic
    networks:
      - default
    depends_on:
      database:
        restart: true
        condition: service_healthy
        required: true
  
  database:
    # mysql --default-character-set=utf8mb4
    image: mysql:8
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u ${MYSQL_USER} -p${MYSQL_PASSWORD}"]
      interval: 30s
      retries: 10
      start_period: 10s
      timeout: 10s
    expose:
      - "3306"


networks:
  default:
    driver: bridge

volumes:
  database-data:
  bot-alembic:
