# Do not edit this file unless you know what you are doing
# All configurations should be set up in .env file before building image

from os import getenv

### Temp variable
# This variable serves as a temporarly storage for a service data. It should not be assigned manually

temp = {"startup_time": None}

####################

TOKEN = getenv("TOKEN")

DEV_GUILDS = [int(getenv("DEV_GUILD"), 0)]

MYSQL_USER = getenv("MYSQL_USER")
MYSQL_PASSWORD = getenv("MYSQL_PASSWORD")
MYSQL_DATABASE = getenv("MYSQL_DATABASE")
MYSQL_HOST = "database"
MYSQL_PORT = "3306"

JWT_SECRET = getenv("JWT_SECRET")
JWT_ALGORITHM = getenv("JWT_ALGORITHM")

DEFAULT_POST_TITLES = {
    0: None,
    1: getenv("FIRST_LVL_POST_TITLE"),
    2: getenv("SECOND_LVL_POST_TITLE"),
    3: getenv("THIRD_LVL_POST_TITLE"),
    4: getenv("FOURTH_LVL_POST_TITLE"),
    5: getenv("FIFTH_LVL_POST_TITLE"),
}

REUSABLE_EMOJI = {
    "pending": getenv("PENDING_EMOJI"),
    "success": getenv("SUCCESS_EMOJI"),
    "fail": getenv("FAILED_EMOJI")
}
